apiVersion: apps/v1
kind: Deployment
metadata:
  name: hris-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hris-app
  template:
    metadata:
      labels:
        app: hris-app
    spec:
      containers:
        - name: hris-app
          image: penicili/hris-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "mysql://hrisapp:hrisdevdbpassword@mysql:3306/hris_dev"
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: hrisapp
            - name: DB_PASSWORD
              value: hrisdevdbpassword
            - name: DB_NAME
              value: hris_dev
            - name: APP_HOST
              value: 0.0.0.0
            - name: APP_PORT
              value: "3000"
            - name: JWT_SECRET
              value: your-secret
            - name: JWT_TTL
              value: "86400"

---
apiVersion: v1
kind: Service
metadata:
  name: hris-app
spec:
  selector:
    app: hris-app
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort