apiVersion: apps/v1
kind: Deployment
metadata:
  name: hris-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hris-backend
  template:
    metadata:
      labels:
        app: hris-backend
    spec:
      containers:
        - name: hris-app
          image: penicili/hris-anu-be:c608e25
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "mysql://hrisapp:hrisdevdbpassword@mysql:3306/hris_dev"
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: hrisapp
            - name: DB_PASSWORD
              value: hrisdevdbpassword
            - name: DB_NAME
              value: hris_dev
            - name: APP_HOST
              value: 0.0.0.0
            - name: APP_PORT
              value: "3000"
            - name: JWT_SECRET
              value: dad53e7599fecbc5e16f9d04e8ca9be36090595f857b1b342cd3f94e172e3a3e
            - name: JWT_TTL
              value: "86400"

---
apiVersion: v1
kind: Service
metadata:
  name: hris-backend
spec:
  selector:
    app: hris-backend
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort