apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: hrisapp
type: Opaque
stringData:
  DATABASE_URL: "mysql://hrisapp:hrisdevdbpassword@mysql:3306/hris_dev"
  DB_USERNAME: "hrisapp"
  DB_PASSWORD: "hrisdevdbpassword"
  JWT_SECRET: "dad53e7599fecbc5e16f9d04e8ca9be36090595f857b1b342cd3f94e172e3a3e"
  MYSQL_DATABASE: "hris_dev"
  MYSQL_USER: "hrisapp"
  MYSQL_PASSWORD: "hrisdevdbpassword"
  MYSQL_ROOT_PASSWORD: "hrisdevdbpassword"
